services:
  backend:
    build:
      context: .\todo-api
    env_file:
      - .\todo-api\.env.production
    ports:
      - 3001:3001
    networks:
      - public-tier
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - db-data:/data/db
    networks:
      - public-tier
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  frontend:
    build:
      context: .\todo-app
    env_file:
      - .\todo-app\.env.production
    ports:
      - 3000:80
    networks:
      - public-tier
    depends_on:
      - backend

volumes:
  db-data:
networks:
  public-tier: