name: Build Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push todo-api
        uses: docker/build-push-action@v5
        with:
          context: ./todo-api
          file: ./todo-api/Dockerfile
          push: true
          tags: castrofernando13/todo-api:latest

      - name: Build and push todo-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./todo-app
          file: ./todo-app/Dockerfile
          push: true
          tags: castrofernando13/todo-frontend:latest
